
add_subdirectory(hello_gui_v2)
add_subdirectory(hello_layout_v2)

# add_subdirectory(hello_file)
# add_subdirectory(hello_file2)
# add_subdirectory(hello_gl)
# add_subdirectory(hello_image)
# add_subdirectory(hello_image_zoom)
# add_subdirectory(hello_plot)
# add_subdirectory(hello_shader)
# add_subdirectory(test_app)
