//  Copyright (c) 2026 Daniel Moreno. All rights reserved.
//
#pragma once

#include <gui2/Widget.hpp>
#include <gui2/Identifier.hpp>
#include <gui2/Actions.hpp>

namespace gui2
{
  //! \brief A Panel is a container that can hold a Widget as its content.
  //!
  //! A panel defines a rectangular area where to draw additional content, which
  //! is provided by a Widget. The panel has a identifier which must be unique
  //! within the application.
  class Panel
  {
  public:
    //! \brief Constructs a Panel with the given identifier.
    //! \param[in] id     The identifier of the panel. It must be unique within
    //!                   the application.
    //! \param[in] widget The content of the panel, which is a Widget.
    template<Identifier T>
    Panel(T&& id, Widget widget = {});

    //! \brief Constructs a Panel with a unique identifier generated from the
    //!        source location where the constructor is called.
    //! \param[in] widget The content of the panel, which is a Widget.
    //! \param[in] location The source location where the panel is constructed.
    Panel(Widget widget = {},
          std::source_location location = std::source_location::current());

    //! \brief Returns the identifier of the panel.
    //!
    //! The identifier returned by this function is generated by the particular
    //! identifier type used to construct the panel. It usually is a string
    //! representation of a hash value computed from the identifier's name or
    //! from the source location where the panel was constructed.
    const std::string& getId() const { return id_; }

    //! \brief Returns the name of the panel.
    //!
    //! If the identifier type used to construct the panel provides a name, this
    //! function returns that name. Otherwise, it returns an empty string. For
    //! example, if the panel was constructed with a StringId, this function
    //! returns the string name of the identifier.
    const std::string& getName() const { return name_; }

    //! \brief Sets whether the panel should draw a border around its content.
    //! \param[in] drawBorder true to draw a border, false to not draw a border.
    void setDrawBorder(bool drawBorder) { drawBorder_ = drawBorder; }

    //! \brief Returns whether the panel should draw a border around its content.
    //! \return true if the panel should draw a border, false otherwise.
    bool getDrawBorder() const { return drawBorder_; }

    //! \brief Adds an action to be executed during the next display cycle.
    //! \param[in] action The action to add.
    //!
    //! Actions are executed during the next display cycle of the text box and
    //! are cleared after being executed. Actions not applicable to this item
    //! are ignored.
    void addAction(Actions action) { actions_ |= action; }

    //! \brief Takes and clears all existing actions.
    //! \return The actions that were taken.
    Actions takeActions() { return std::exchange(actions_, Actions::None); }

    //! \brief Displays the content of the panel using the given runtime and
    //!        rectangle.
    //! \param[in] runtime The runtime used to display the content.
    //! \param[in] rect    The rectangle where the content is displayed.
    //! \return The actual rectangle used to display the content, which may be
    //!         different from the requested rectangle.
    Rect displayContent(const Runtime& runtime, const Rect& rect);

  private:
    std::string id_;
    std::string name_;
    Widget widget_;
    bool drawBorder_ = true;
    Actions actions_ = Actions::None;
  };

} // namespace gui

// Implementation ------------------------------------------------------------
namespace gui2
{
  template<Identifier T>
  Panel::Panel(T&& id, Widget widget)
    : widget_{std::move(widget)}
    , id_{id.getValueStr()}
  {
    if constexpr (IdentifierWithName<std::remove_cvref_t<T>>)
    {
      name_ = id.getName();
    }
  }

  inline Panel::Panel(Widget widget, std::source_location location)
    : widget_{std::move(widget)}
  {
    LocationId id{std::move(location)};
    id_ = id.getValueStr();
  }

  inline Rect Panel::displayContent(const Runtime& runtime, const Rect& rect)
  {
    return widget_.display(runtime, rect );
  }
}
