//  Copyright (c) 2026 Daniel Moreno. All rights reserved.
//
#pragma once

#include <gui2/Widget.hpp>
#include <gui2/Identifier.hpp>

namespace gui2
{
  //! \brief A TextBox is a GUI widget that allows the user to input and edit
  //!        text.
  class TextBox
  {
  public:
    //! \brief Constructs a TextBox with the given identifier and a pointer to
    //!        a string that holds the text content of the TextBox.
    //! \param[in] id   The identifier of the TextBox. It must be unique within
    //!                 the application.
    //! \param[in] text A pointer to a string that holds the text content of the
    //!                 TextBox. The TextBox does not take ownership of the
    //!                 string, and the caller is responsible for ensuring that
    //!                 the string remains valid for the lifetime of the TextBox.
    template<Identifier T>
    TextBox(T&& id, std::string* text);

    //! \brief Constructs a TextBox with a unique identifier generated from the
    //!        source location where the constructor is called, and a pointer to
    //!        a string that holds the text content of the TextBox.
    //! \param[in] text A pointer to a string that holds the text content of the
    //!                 TextBox. The TextBox does not take ownership of the
    //!                 string, and the caller is responsible for ensuring that
    //!                 the string remains valid for the lifetime of the TextBox.
    //! \param[in] location The source location where the TextBox is constructed.
    TextBox(std::string* text,
            std::source_location location = std::source_location::current());

    //! \brief Returns the identifier of the text box.
    //!
    //! The identifier returned by this function is generated by the particular
    //! identifier type used at construction time. It usually is a string
    //! representation of a hash value computed from the identifier's name or
    //! from the source location where the object was constructed.
    const std::string& getId() const { return id_; }

    //! \brief Returns the name of the text box.
    //!
    //! If the identifier type used at construction time provides a name, this
    //! function returns that name. Otherwise, it returns an empty string. For
    //! example, if the text box was constructed with a StringId, this function
    //! returns the string name of the identifier.
    const std::string& getName() const { return name_; }

    //! \brief Returns the text content of the text box.
    //! \return The text content of the text box.
    std::string* getTextPtr()  { return text_; }

  private:
    std::string id_;
    std::string name_;
    std::string* text_;
  };

} // namespace gui

// Implementation ------------------------------------------------------------
namespace gui2
{
  template<Identifier T>
  TextBox::TextBox(T&& id, std::string* text)
    : text_{text}
    , id_{id.getValueStr()}
  {
    if constexpr (IdentifierWithName<std::remove_cvref_t<T>>)
    {
      name_ = id.getName();
    }
  }

  inline TextBox::TextBox(std::string* text, std::source_location location)
    : text_{text}
  {
    LocationId id{std::move(location)};
    id_ = id.getValueStr();
  }
}
