name: Build and Test (Ubuntu)

on:
  push:
    branches: [ main ]
  workflow_dispatch: # manually trigger the workflow

permissions:
  checks: write
  actions: read
  contents: read

jobs:

  build-ubuntu:
    name: Ubuntu-Build (GLFW_GL3)
    runs-on: ubuntu-26.04
    env:
      # ubuntu-26-04: Fix the version of GCC to 15 to have a consistent build
      # environment. The default GCC version is 15, but it could change in the
      # future.
      CC: gcc-15
      CXX: g++-15

    steps:

    - name: Checkout source code
      uses: actions/checkout@v5.0.0

    - name: Install Linux Dependencies
      run: |
        sudo apt update
        sudo apt install  \
          libxrandr-dev   \
          libxinerama-dev \
          libxcursor-dev  \
          libxi-dev       \
          libgl-dev       \
          libgtk-3-dev

    - name: Configure and Build
      run: ${{github.workspace}}/build.sh

  build-tests-ubuntu:
    name: Ubuntu-Build (Tests)
    runs-on: ubuntu-26.04

    env:
      PRESET_NAME: gcc-linux-release
      # ubuntu-26-04: Fix the version of GCC to 15 to have a consistent build
      # environment. The default GCC version is 15, but it could change in the
      # future.
      CC: gcc-15
      CXX: g++-15
      CMAKE_CONFIG_OPTIONS: -DUSE_GLFW_GL3=0 -DUSE_GUI_TEST_ENGINE=1

    steps:

    - name: Checkout source code
      uses: actions/checkout@v5.0.0

    - name: Configure and Build
      run: |
        cmake --preset ${{ env.PRESET_NAME }} ${{ env.CMAKE_CONFIG_OPTIONS }} && \
        cmake --build --preset "${{ env.PRESET_NAME }}" -j

    - name: Run Tests
      run: |
        export GUI_TEST_MARKDOWN_REPORT_FILE=${{github.workspace}}/gui_test_report.md
        ${{github.workspace}}/build/release/bin/hello_gui
        cat $GUI_TEST_MARKDOWN_REPORT_FILE >> $GITHUB_STEP_SUMMARY
