name: Build and Test (macOS)

on:
  workflow_dispatch: # manually trigger the workflow
    inputs:
      runner:
        description: Runner
        required: true
        type: choice
        default: macos-15
        options:
          - macos-14          # macOS 14 (Sonoma) - arm64
          - macos-14-large    # macOS 14 (Sonoma) - x64
          - macos-15          # macOS 15 (Sequoia) - arm64
          - macos-15-intel    # macOS 15 (Sequoia) - x64
          - macos-26          # macOS 26 (Tahoe) - arm64
          - macos-26-intel    # macOS 26 (Tahoe) - x64

permissions:
  checks: write
  actions: read
  contents: read

jobs:

  build-macos:
    name: macOS-Build (GLFW_GL3)
    runs-on: ${{ inputs.runner || 'macos-15' }}
    steps:

    - name: Checkout source code
      uses: actions/checkout@v7.0.1

    - name: Configure and Build
      run: ${{github.workspace}}/build.sh

  build-tests-macos:
    name: macOS-Build (Tests)
    runs-on: ${{ inputs.runner || 'macos-15' }}

    env:
      PRESET_NAME: clang-macos-release
      CMAKE_CONFIG_OPTIONS: -DUSE_GLFW_GL3=0 -DUSE_GUI_TEST_ENGINE=1

    steps:

    - name: Checkout source code
      uses: actions/checkout@v7.0.1

    - name: Configure and Build
      run: |
        cmake --preset ${{ env.PRESET_NAME }} ${{ env.CMAKE_CONFIG_OPTIONS }} && \
        cmake --build --preset "${{ env.PRESET_NAME }}" -j

    - name: Run Tests
      run: |
        export GUI_TEST_MARKDOWN_REPORT_FILE=${{github.workspace}}/gui_test_report.md
        ${{github.workspace}}/build/release/bin/hello_gui
        cat $GUI_TEST_MARKDOWN_REPORT_FILE >> $GITHUB_STEP_SUMMARY
